hey: one two
    # Outputs "hey", since this is the target name
	@echo $@

    # Outputs the first prerequisite using $< (it will print "one")
	@echo "The first prerequisite is: $<"
    
    # Outputs all prerequisites newer than the target
	@echo $?

    # Outputs all prerequisites
	@echo $^
	@touch hey

one:
	@touch one

two:
	@touch two

clean:
	rm -f hey one two
	@echo "Current date and time: $$(date)"


