.PHONY: all clean

all: target1 target2 target3

target1:
	@echo "Building target1"
	-./command1

target2:
	@echo "Building target2"
	./command2

target3:
	@echo "Building target3"
	./command3

clean:
	@echo "Cleaning up"
	rm -rf *.o


